apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivbirt
  name: {{ template "aivhub.fullname" . }}-aivbirt
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.aivbirt.service.type }}
  ports:
    - name: http
      port: 9990
      targetPort: 9990
  selector:
    app: {{ template "aivhub.fullname" . }}-aivbirt