apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivbirt
  name: {{ template "aivhub.fullname" . }}-aivbirt
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.aivbirt.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "aivhub.fullname" . }}-aivbirt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "aivhub.fullname" . }}-aivbirt
        test: db
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity  }}
      affinity:
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: AIV_CORE
              value: http://{{ template "aivhub.fullname" . }}-core.{{ .Release.Namespace }}:9998
            - name: AIV_DATA
              value: http://{{ template "aivhub.fullname" . }}-aivdata.{{ .Release.Namespace }}:9013
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.postgres.Password }}"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ template "aivhub.fullname" . }}-metadata.{{ .Release.Namespace }}:5432/aiv5
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.User }}"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: jits023/aiv:{{ .Values.aivbirt.image.tag }}
          imagePullPolicy: {{ .Values.aivbirt.image.pullPolicy }}
          name: {{ .Chart.Name }}-aivbirt
          ports:
            - name: http
              containerPort: 9990
          resources: 
            {{- if .Values.aivbirt.resources }}
              {{- toYaml .Values.aivbirt.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /opt/repository
              name: repository-ps
              readOnly: false
            - mountPath: /opt/logs
              name: logs-ps
              readOnly: false
      initContainers:
        - name: init-downloader
          image: amazon/aws-cli:latest
          command: ['sh', '-c', "aws s3 sync s3://{{ .Values.s3BucketRepository }}/repository/ /opt/repository"]
          env:
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.aws.accessKey }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.aws.secretKey }}
          - name: AWS_REGION
            value: {{ .Values.aws.region }}
          volumeMounts:
            - mountPath: /opt/repository
              name: repository-ps
      volumes:
        - name: repository-ps
          persistentVolumeClaim:
            claimName: {{ template "aivhub.fullname" . }}-pvc-repository
        - name: logs-ps
          persistentVolumeClaim:
            claimName: {{ template "aivhub.fullname" . }}-pvc-logs