apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivdata
  name: {{ template "aivhub.fullname" . }}-aivdata
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.aivdata.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "aivhub.fullname" . }}-aivdata
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "aivhub.fullname" . }}-aivdata
        test: db
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity  }}
      affinity:
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: AIV_CORE
              value: http://{{ template "aivhub.fullname" . }}-core.{{ .Release.Namespace }}:9998
            - name: CLASSICMODEL_DS_URL
              value: jdbc:mysql://aws.connect.psdb.cloud:3306/classicmodels
            - name: CLASSICMODEL_PASSWORD
              value: pscale_pw_6i5m9HTsVXCiNnQoXtyFuVPu8AJ6W4DsJ1WvLRa0Bew
            - name: CLASSICMODEL_USERNAME
              value: g4cbf7tym07m0agzzg4r
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: jits023/aiv:{{ .Values.aivdata.image.tag }}
          imagePullPolicy: {{ .Values.aivdata.image.pullPolicy }}
          name: {{ .Chart.Name }}-aivdata
          ports:
            - name: http
              containerPort: 9013
          resources: 
            {{- if .Values.aivdata.resources }}
              {{- toYaml .Values.aivdata.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /opt/repository
              name: repository-ps
              readOnly: false
            - mountPath: /opt/logs
              name: logs-ps
              readOnly: false
      initContainers:
        - name: init-downloader
          image: amazon/aws-cli:latest
          command: ['sh', '-c', "aws s3 sync s3://{{ .Values.s3BucketRepository }}/repository/ /opt/repository"]
          env:
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.aws.accessKey }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.aws.secretKey }}
          - name: AWS_REGION
            value: {{ .Values.aws.region }}
          volumeMounts:
            - mountPath: /opt/repository
              name: repository-ps
      volumes:
        - name: repository-ps
          persistentVolumeClaim:
            claimName: {{ template "aivhub.fullname" . }}-pvc-repository
        - name: logs-ps
          persistentVolumeClaim:
            claimName: {{ template "aivhub.fullname" . }}-pvc-logs