apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivdata
  name: {{ template "aivhub.fullname" . }}-aivdata
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.aivdata.service.type }}
  ports:
    - name: http
      port: 9013
      targetPort: 9013
  selector:
    app: {{ template "aivhub.fullname" . }}-aivdata