apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivpentaho
  name: {{ template "aivhub.fullname" . }}-aivpentaho
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.aivpentaho.service.type }}
  ports:
    - name: http
      port: 9994
      targetPort: 9994
  selector:
    app: {{ template "aivhub.fullname" . }}-aivpentaho