{{- if .Values.aivsecuritykeycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-aivsecuritykeycloak
  name: {{ template "aivhub.fullname" . }}-aivsecuritykeycloak
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.aivsecuritykeycloak.service.type }}
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: {{ template "aivhub.fullname" . }}-aivsecuritykeycloak
{{- end -}}