{{- if .Values.awsHosted.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "aivhub.fullname" . }}-pv-repository
spec:
  capacity:
    storage: {{ .Values.repository.persistence.storageSize }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.repository.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.awsHosted.efs.id }}
{{- end -}}