{{- if .Values.awsHosted.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "aivhub.fullname" . }}-pv-metadata
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-9"
spec:
  capacity:
    storage: {{ .Values.metadata.persistence.storageSize }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.metadata.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.awsHosted.efs.id }}
{{- end -}}