apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-core
  name: {{ template "aivhub.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - name: http
      port: 9998
      targetPort: 9998
  selector:
    app: {{ template "aivhub.fullname" . }}-core