apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "aivhub.fullname" . }}-gateway
  name: {{ template "aivhub.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: 9001
      targetPort: 9001
  selector:
    app: {{ template "aivhub.fullname" . }}-gateway
