{{- if .Values.googleHosted.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "aivhub.fullname" . }}-pv-repository
spec:
  capacity:
    storage: {{ .Values.repository.persistence.storageSize }}
  accessModes:
    - {{ .Values.repository.persistence.accessMode }}
  nfs:
    server: {{ .Values.googleHosted.nfs.server }}
    path: {{ .Values.googleHosted.nfs.path }}
{{- end -}}