{{- if .Values.googleHosted.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "aivhub.fullname" . }}-pvc-metadata
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: ""
  volumeName: {{ template "aivhub.fullname" . }}-pv-metadata
  accessModes:
    - {{ .Values.metadata.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.metadata.persistence.storageSize }}
{{- end -}}