{{- if or (.Values.selfHosted.enabled) (.Values.azureHosted.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "aivhub.fullname" . }}-pvc-logs
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.logs.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.logs.persistence.storageSize }}
{{- end -}}