apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aivhub.fullname" . }}-metadata
  name: {{ template "aivhub.fullname" . }}-metadata
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
spec:
  type: {{ .Values.metadata.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ template "aivhub.fullname" . }}-metadata
